//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniOBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOgrenciNot
    {
        public int OgrenciNotID { get; set; }
        public int OgrenciId { get; set; }
        public string OgrenciNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int DersId { get; set; }
        public string DersAd { get; set; }
        public string SinavTuru { get; set; }
        public string SinavNotu { get; set; }
    }
}
