//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniOBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinif
    {
        public Sinif()
        {
            this.Ogrenci = new HashSet<Ogrenci>();
        }
    
        public int SinifID { get; set; }
        public string SinifAd { get; set; }
    
        public virtual ICollection<Ogrenci> Ogrenci { get; set; }
    }
}
