//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniOBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOgrenci
    {
        public int OgrenciID { get; set; }
        public string OgrenciNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public byte[] Resim { get; set; }
        public Nullable<int> SinifId { get; set; }
        public string SinifAd { get; set; }
    }
}
